### ISSUE TITLE
Const generics on ArrayString

### ISSUE THREAD

**Issue by chris-morgan** [ThatsNoMoon/tinyvec_string#3]
The necessary stuff was released in stable Rust in 1.55.0 a few months ago, and tinyvec has a rust_1_55 feature to enable it for `Array`. This crate should either follow the same pattern or just enable it unconditionally if willing to bump the MSRV (that’s what I’d suggest at this pre-1.0 stage).

**Comment by ThatsNoMoon** [comment]
Thanks for reminding me; I actually already have an implementation of that feature, among others, on a separate branch. I'll push an update shortly.
